// flow-typed signature: 597b7a13e0b910b1dc591775393bfbe5
// flow-typed version: <<STUB>>/clear_v^0.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clear'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clear' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clear/examples/clear' {
  declare module.exports: any;
}

declare module 'clear/examples/delay-clear' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clear/examples/clear.js' {
  declare module.exports: $Exports<'clear/examples/clear'>;
}
declare module 'clear/examples/delay-clear.js' {
  declare module.exports: $Exports<'clear/examples/delay-clear'>;
}
declare module 'clear/index' {
  declare module.exports: $Exports<'clear'>;
}
declare module 'clear/index.js' {
  declare module.exports: $Exports<'clear'>;
}
