// flow-typed signature: 21de1736655de1f2c5ae2eacc4c9fb14
// flow-typed version: <<STUB>>/clui_v^0.3.6/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clui/examples/buffer' {
  declare module.exports: any;
}

declare module 'clui/examples/gauges' {
  declare module.exports: any;
}

declare module 'clui/examples/progress' {
  declare module.exports: any;
}

declare module 'clui/examples/simpleColumns' {
  declare module.exports: any;
}

declare module 'clui/examples/spinner' {
  declare module.exports: any;
}

declare module 'clui/lib/clui' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clui/examples/buffer.js' {
  declare module.exports: $Exports<'clui/examples/buffer'>;
}
declare module 'clui/examples/gauges.js' {
  declare module.exports: $Exports<'clui/examples/gauges'>;
}
declare module 'clui/examples/progress.js' {
  declare module.exports: $Exports<'clui/examples/progress'>;
}
declare module 'clui/examples/simpleColumns.js' {
  declare module.exports: $Exports<'clui/examples/simpleColumns'>;
}
declare module 'clui/examples/spinner.js' {
  declare module.exports: $Exports<'clui/examples/spinner'>;
}
declare module 'clui/lib/clui.js' {
  declare module.exports: $Exports<'clui/lib/clui'>;
}
