// flow-typed signature: 43250b816ad5992fdb0c767b5aa59daf
// flow-typed version: <<STUB>>/node-binance-api_v^0.4.21/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-binance-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-binance-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-binance-api/examples/example' {
  declare module.exports: any;
}

declare module 'node-binance-api/node-binance-api' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-binance-api/examples/example.js' {
  declare module.exports: $Exports<'node-binance-api/examples/example'>;
}
declare module 'node-binance-api/node-binance-api.js' {
  declare module.exports: $Exports<'node-binance-api/node-binance-api'>;
}
